"""
Reporting Service for Credit Scoring System.

Generates PDF, CSV, and TXT credit evaluation certificates.
"""

from datetime import datetime
from typing import Dict, Any
from fpdf import FPDF


def generate_txt_report(result: Dict[str, Any], applicant_name: str = "Anonymous Applicant") -> str:
    """Generates plain text credit assessment report."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    return f"""==================================================
CREDIT RISK ASSESSMENT SUMMARY CERTIFICATE
==================================================
Applicant Name: {applicant_name}
Evaluation Date: {timestamp}

UNDERWRITING DECISION
--------------------------------------------------
Decision Status: {result['status']}
Approval Probability: {result['probability_pct']}%
Risk Level Category: {result['risk_level']}
Debt-to-Income (DTI): {result['dti_ratio']}%

DECISION EXPLANATIONS & RISK FACTORS
--------------------------------------------------
""" + "\n".join([f"- {item}" for item in result.get("explanations", [])]) + f"""

DISCLAIMER:
This AI Credit Scoring Report is designed as a decision-support tool.
Final loan approval must be validated by a certified credit underwriter.
=================================================="""


def generate_csv_report(result: Dict[str, Any], applicant_name: str = "Anonymous Applicant") -> str:
    """Generates CSV string for credit evaluation metrics."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines = [
        "Applicant Name,Decision Status,Approval Probability %,Risk Category,Debt-to-Income %,Timestamp",
        f'"{applicant_name}","{result["status"]}",{result["probability_pct"]},"{result["risk_level"]}",{result["dti_ratio"]},"{timestamp}"'
    ]
    return "\n".join(lines)


def generate_pdf_report(result: Dict[str, Any], applicant_name: str = "Anonymous Applicant") -> bytes:
    """Generates a professional PDF credit certificate using FPDF with safe margins."""
    try:
        pdf = FPDF()
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.add_page()
        pdf.set_margins(15, 15, 15)

        # Header Title
        pdf.set_font("Helvetica", "B", 16)
        pdf.set_text_color(30, 58, 138)  # Royal Navy Blue
        pdf.cell(180, 10, "CREDIT RISK EVALUATION CERTIFICATE", ln=True, align="C")
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(100, 116, 139)
        pdf.cell(180, 6, "AI-Powered Financial Decision System", ln=True, align="C")
        pdf.ln(6)

        # Applicant Info Box
        pdf.set_fill_color(241, 245, 249)
        pdf.rect(15, pdf.get_y(), 180, 24, "F")
        pdf.set_xy(18, pdf.get_y() + 3)
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(15, 23, 42)
        pdf.cell(85, 6, f"Applicant Name: {applicant_name}")
        pdf.cell(85, 6, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}", ln=True)
        pdf.set_x(18)
        pdf.cell(85, 6, f"Debt-to-Income Ratio: {result['dti_ratio']}%")
        pdf.cell(85, 6, f"Certificate ID: CRD-{int(datetime.now().timestamp())}", ln=True)
        pdf.ln(10)

        # Decision Result Summary
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(30, 58, 138)
        pdf.cell(180, 8, "Underwriting Decision & Risk Classification", ln=True)
        pdf.line(15, pdf.get_y(), 195, pdf.get_y())
        pdf.ln(4)

        pdf.set_font("Helvetica", "", 11)
        pdf.set_text_color(30, 41, 59)
        pdf.cell(60, 7, "Decision Status:")
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(120, 7, f"{result['status']}", ln=True)

        pdf.set_font("Helvetica", "", 11)
        pdf.cell(60, 7, "Approval Probability:")
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(120, 7, f"{result['probability_pct']}%", ln=True)

        pdf.set_font("Helvetica", "", 11)
        pdf.cell(60, 7, "Risk Classification:")
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(120, 7, f"{result['risk_level']}", ln=True)
        pdf.ln(6)

        # Key Factors
        pdf.set_font("Helvetica", "B", 12)
        pdf.set_text_color(30, 58, 138)
        pdf.cell(180, 8, "Key Financial Observations", ln=True)
        pdf.line(15, pdf.get_y(), 195, pdf.get_y())
        pdf.ln(4)

        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(51, 65, 85)
        for exp in result.get("explanations", []):
            clean_exp = exp.replace("✅", "[+]").replace("⚠️", "[!]").replace("🔴", "[-]").replace("ℹ️", "[i]")
            pdf.multi_cell(180, 6, f"- {clean_exp}")
            pdf.set_x(15)
        pdf.ln(6)

        # Disclaimer
        pdf.set_font("Helvetica", "I", 8)
        pdf.set_text_color(148, 163, 184)
        pdf.multi_cell(180, 5, "DISCLAIMER: This report is generated by an automated Machine Learning credit scoring engine. Final credit decisions must comply with local banking regulatory frameworks.")

        return bytes(pdf.output())
    except Exception as e:
        txt_content = generate_txt_report(result, applicant_name)
        return txt_content.encode("utf-8")
